name: Recommendation Pipeline

# Manualy and daily triggered

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

permissions:
  contents: write

jobs:
  recommend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r recommend_system/requirements.txt

      - name: Fetch latest papers
        run: |
          python recommend_system/script/craw_arxiv.py
      
      - name: Build embeddings
        env:
          EMBEDDING_API_KEY : ${{ secrets.EMBEDDING_API_KEY }}
        run: |
          python recommend_system/script/build_embed.py

      - name: Fit & Predict
        run: |
          python recommend_system/script/fit_model.py

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: data/visualizations

      - name: AI summary
        env:
          SUMMARY_API_KEY : ${{ secrets.SUMMARY_API_KEY }}
        run: |
          python recommend_system/script/ai_summary.py

      - name: Git commit
        run: |
          git add ./website/src/content/
          git commit -m "Daily Paper Recommendation"
          git push